### ISSUE TITLE
Trained weights

### ISSUE THREAD

**Issue by ofirkris** [Riretta/Colourisation_w_Capsules#1]
Hello, I'm researching colorization - this looks really great!
Can you share inference example + trained checkpoints?

**Comment by Riretta** [comment]
Hi!
thank you for the interest! Inference examples are on the paper linked, I
will add a folder to the github with other examples, thanks for the
suggestion.
For the checkpoints as soon as I reach my lab pc I can share!

Rita

                **Rita Pucci** ~ https://ritapucci.wordpress.com/
rita.pucci85@gmail.com || rita.pucci@uniud.it || riretta@hotmail.com ||
puccir@cli.di.unipi.it


Il giorno sab 12 dic 2020 alle ore 20:33 ofirkris <notifications@github.com>
ha scritto:

**Comment by Riretta** [comment]
Done
